version: '2'
services:
  plexmediaserver:
    container_name: PlexMediaServer
    restart: unless-stopped
    image: linuxserver/plex:latest
    environment:
      - TZ=America/Chicago
      - VERSION=latest
      - PLEX_CLAIM="claim-wPH9wmSvx1frsxFuR3is"
      - network_mode=host
    ports:
      - "32400:32400" #(for access to the Plex Media Server) [required]
    volumes:
      - /mnt/md0/docker/PlopServer/PlexMediaServer/Config:/config
      - /mnt/md0/docker/PlopServer/PlexMediaServer/Media/Movies:/data/movies
      - /mnt/md0/docker/PlopServer/PlexMediaServer/Media/TVShows:/data/tvshows
      - /mnt/md0/docker/PlopServer/PlexMediaServer/Media/Music:/data/music
      - /mnt/md0/docker/PlopServer/PlexMediaServer/Media/HomeMedia:/data/homemedia
      - /mnt/md0/docker/PlopServer/PlexMediaServer/Media/Photos:/data/photos
    networks:
      homenet:
        ipv4_address: 10.0.0.2
  plextransmission:
    container_name: Transmission
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - "9091:9091"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/md0/docker/PlopServer/Transmission:/data
      - /mnt/md0/docker/PlopServer/Transmission/shared:/shared
      - /mnt/md0/docker/PlopServer/Transmission/Downloads:/data/watch
      - /mnt/md0/docker/PlopServer/Transmission/completed:/data/completed
      - /mnt/md0/docker/PlopServer/Transmission/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=IPVANISH
      - OPENVPN_USERNAME=ahumphries003@gmail.com
      - OPENVPN_PASSWORD=Humps003
      - OPENVPN_CONFIG="mke-c02.ipvanish.com"
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=1000
      - PGID=1001
      - TZ=America/Chicago
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_PASSWORD=Humps003
      - TRANSMISSION_RPC_USERNAME=administrator
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
    networks:
      homenet:
        ipv4_address: 10.0.0.3
  plexradarr:
    image: "linuxserver/radarr"
    container_name: "Radarr"
    volumes:
      - /mnt/md0/docker/PlopServer/Radarr/config:/config
      - /mnt/md0/docker/PlopServer/PlexMediaServer/Media/Movies:/movies
      - /mnt/md0/docker/PlopServer/Transmission/completed:/data/completed
    ports:
      - "7878:7878"
    restart: always
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/Chicago
    networks:
      homenet:
        ipv4_address: 10.0.0.4
  plexsonarr:
    image: linuxserver/sonarr
    container_name: Sonarr
    restart: always
    ports:
      - "8989:8989"
    networks:
      homenet:
        ipv4_address: 10.0.0.5
    environment:
      - PGID=1001
      - PUID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/md0/docker/PlopServer/Sonarr/config:/config
      - /mnt/md0/docker/PlopServer/PlexMediaServer/Media/TVShows:/tv
      - /mnt/md0/docker/PlopServer/Transmission/completed:/data/completed
  plexheadphones:
    image: linuxserver/headphones
    container_name: Headphones
    restart: always
    ports:
      - "8181:8181"
    networks:
      homenet:
        ipv4_address: 10.0.0.6
    environment:
      - PGID=1001
      - PUID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/md0/docker/PlopServer/Headphones/config:/config
      - /mnt/md0/docker/PlopServer/PlexMediaServer/Media/Music:/music
      - /mnt/md0/docker/PlopServer/Transmission/completed:/data/completed
  plexjackett:
    image: linuxserver/jackett
    container_name: Jackett
    restart: always
    networks:
      - homenet
    environment:
      - PGID=1000
      - PUID=1001
      - TZ=America/Chicago
    volumes:
      - /mnt/md0/docker/PlopServer/Jackett/config:/config
      - /mnt/md0/docker/PlopServer/Jackett/downloads:/downloads
    ports:
      - "9117:9117"
    networks:
      homenet:
        ipv4_address: 10.0.0.7
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=administrator
      - MYSQL_PASSWORD=Humps003
      - MYSQL_ROOT_PASSWORD=root
      - PGID=1001
      - PUID=1000
    volumes:
      - /mnt/md0/docker/PlopServer/NextCloud/db:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always
    networks:
      homenet:
        ipv4_address: 10.0.0.8
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PhpMyAdmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: administrator
      MYSQL_PASSWORD: Humps003
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "80:80"
    links:
      # for mysql container
      - "db:db"
    restart: always
    networks:
      homenet:
        ipv4_address: 10.0.0.9
  nextcloud:
    container_name: NextCloud
    image: nextcloud
    ports:
      - 800:80
    links:
      - db
    volumes:
      - /mnt/md0/docker/PlopServer/NextCloud/appdata:/var/www/html
      - /mnt/md0/docker/PlopServer/PlexMediaServer/Media:/mnt/md0/plex/PlexMediaServer
    restart: always
    environment:
      - PGID=1001
      - PUID=1000
      - MYSQLDATABASE=nextcloud
      - MYSQLUSER=administrator
      - MYSQL_PASSWORD=Humps003
      - MYSQL_HOST=10.0.0.8
    networks:
      homenet:
        ipv4_address: 10.0.0.10
  homeassistant:
    container_name: HomeAssistant
    image: homeassistant/home-assistant
    volumes:
      - /mnt/md0/docker/PlopServer/HomeAssistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "8123:8123"
    networks:
      homenet:
        ipv4_address: 10.0.0.11
  lazylibrarian:
    container_name: LazyLibrarian
    image: linuxserver/lazylibrarian:latest
    volumes:
      - /mnt/md0/docker/PlopServer/LazyLibrarian/config:/config
      - /mnt/md0/docker/PlopServer/LazyLibrarian/Books:/books
      - /mnt/md0/docker/PlopServer/LazyLibrarian/downloads:/downloads
    restart: unless-stopped
    environment:
      - PGID=1001
      - PUID=1000
      - TZ=CST
    ports:
      - "5299:5299"
    networks:
      homenet:
        ipv4_address: 10.0.0.12
  mosquitto: #MQTT Broker
    container_name: Mosquitto
    restart: unless-stopped
    image: eclipse-mosquitto:latest
    environment:
      - PUID=1000
      - PGID=1001
    ports:
      - "9001:9001"
      - "1883:1883"
    volumes:
      - /mnt/md0/docker/PlopServer/Mosquitto/config:/mosquitto/config
      - /mnt/md0/docker/PlopServer/Mosquitto/data:/mosquitto/data
      - /mnt/md0/docker/PlopServer/Mosquitto/log:/mosquitto/log
    networks:
      homenet:
        ipv4_address: 10.0.0.13
  docker_mon:
    image: philhawthorne/ha-dockermon
    container_name: HomeAssistantDockerMon
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/md0/docker/PlopServer/HomeAssistantDockerMon/config:/config
    ports:
      - 8126:8126
volumes:
    db:
        driver: "local"
networks:
  homenet:
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/16
        gateway: 10.0.0.1
